### ISSUE TITLE
Speed limits may not be correct

### ISSUE THREAD

**Issue by bdraco** [sbidy/pywizlight#127]
It looks like the devices report a speed of 20-200 instead of 1-100

**Comment by bdraco** [comment]
Looks like its 10-200

**Comment by sbidy** [comment]
True but 20-200 - https://docs.pro.wizconnected.com/#graphql-schema

"speed - type Int, Speed of dynamic light modes (Ocean, Romance, Forest, etc). Valid range: 20-200"

**Comment by sbidy** [comment]
I think this was changed in a FW update to that range. It was initially percentages.

**Comment by bdraco** [comment]
So it looks like if `state: True` is in the message speed will not change

Working on a fix now
