### ISSUE TITLE
Energy data

### ISSUE THREAD

**Issue by bdraco** [sbidy/pywizlight#130]
Investigate if its possible to get energy data from the device to show in Home Assistant

**Comment by bdraco** [comment]
https://gitlab.com/wizlighting/wiz-local-control/-/issues/2

**Comment by sbidy** [comment]
Feedback from WiZ:
Only following modules supports `getPower` message:

  ESP25_SOCKET_01
  ESP20_SHDW_31R
  ESP20_SHRGB_31R
  ESP20_SHTW_31R

**Help wanted:** If someone has one of these types purchased, please give us a hint about type, product and vendor.

**Comment by bdraco** [comment]
It looks like any of the smart plugs manufactured after oct 2021 will have the power monitoring support.  I haven't been able to find a vendor that sells one yet though.

**Comment by danielr1996** [comment]
> Feedback from WiZ: Only following modules supports `getPower` message:
> 
> ESP25_SOCKET_01 ESP20_SHDW_31R ESP20_SHRGB_31R ESP20_SHTW_31R
> 
> **Help wanted:** If someone has one of these types purchased, please give us a hint about type, product and vendor.

Can you tell us what these devices are named on the website? I remember in the wizlight repo (Home Assistant Integration) was a table that had more description for each module type, but I couldn't find it anymore. Maybe people have these devices but don't know it because the internal module type doesn't have any meaning to them or want to buy them to support the project but don't know what to actually buy. 

For those running the WiZ Home Assistant Integration: the internal module type can be looked up in HA under Settings -> Devices & Services -> Devices in the 'Model' column

**Comment by bdraco** [comment]
Thanks for your interest.  We don't know the model numbers of devices that have these modules.  

We do know that smart plugs manufactured after oct 2021 likely have socket module, but after buying from 6 different vendors I've given up trying to find one and will wait until later in the year in the hopes that old inventory is cleared out.

**Comment by timoly** [comment]
I commented on the gitlab issue details about the getPower command which is working correctly with the newer plugs.
https://gitlab.com/wizlighting/wiz-local-control/-/issues/2#note_931657026

**Comment by bdraco** [comment]
Thanks @timoly 

Where did you get the newer plug?

**Comment by timoly** [comment]
> 
Verkkokauppa.com, It's a Finnish shop which unfortunately doesn't ship internationally 
https://www.verkkokauppa.com/fi/product/728039/WiZ-Plug-etaohjattava-pistorasia-sisakayttoon-valkoinen-Wi-F

**Comment by bdraco** [comment]
I picked up 2 US ones locally and they were still the old version unfortunately.

If anyone wants to ship me one, I can add support for them since I have a voltage converter to use for testing.

I have a mailbox in the UK if international shipping is cost prohibitive.   Contact me at nick at koston.org for the address

**Comment by BonnieSoftware** [comment]
You should read the following:
https://taolight.helpshift.com/a/wiz/?s=power-consumption-and-power-outages&f=why-is-there-no-power-consumption-displayed-for-my-device&l=en

"To compute the power consumed by a device, WiZ system uses the regular status report of the devices to the Cloud, associated with reference power consumption data for each mode and brightness, measured in laboratory."

I'm not entirely convinced that reporting energy data that could potentially be incorrect is a good idea.

**Comment by bdraco** [comment]
That's only for the devices that don't report power themselves
