### ISSUE TITLE
How to migrate from wiz_light custom repo to built-in integration

### ISSUE THREAD

**Issue by zachberger** [sbidy/pywizlight#143]
Hey Stephan,

Congrats on the release of the official Wiz integration in Home Assistant!

I was wondering how to migrate from the wiz_light custom integration to the official integration. After upgrading to the latest home assistant release, I tried simply removing the wiz_light integration and restarting, but after this I was not able to control the lights. 

Is there a recommended way to upgrade, or do I need to re-configure all the lights from scratch?

**Comment by bdraco** [comment]
Please see this thread
https://community.home-assistant.io/t/wiz-lights/400223

**Comment by zachberger** [comment]
I have many lights so removing each light and then re-adding them was not ideal. I ended up modifying my .storage/core.config_entries file, replacing "domain": "wiz_light" with "domain": "wiz", and changing each light’s host field with the light’s IP address (the new integration doesn’t seem happy with hostnames).
