### ISSUE TITLE
Auto discovery not working with Philips Wiz Wifi Bulb

### ISSUE THREAD

**Issue by srisham** [sbidy/pywizlight#148]
I am trying to discover the Philips Wiz Wifi Bulb using wizlight cli but the discover option doesn't detect the device.

I tried the following:
1. No response when I use the pywizlight discover option with broadcast IP 255.255.255.255.
2. No response when I use 'nc' Linux command to send UDP packets with the above IP.
3. Able to get a response when I directly use Bulb IP (both 'nc'  and 'discover' option).
4. Able to talk to the device (using bulb IP) such as toggle, get device info, etc.

How to auto-discover this Wiz device on the network?

**Comment by sbidy** [comment]
The discovery works with UDP broadcast messages. It can be possible, that this type of messages are not allowed in your network.

**Comment by srisham** [comment]
Thanks for the response.
Let me check my network settings and try again.

**Comment by WitherredAway** [comment]
Were you able to fix it? I'm facing the same issue and I'm not sure what to do

**Comment by srisham** [comment]
I still facing the issue. But I think it could be an issue with the light that I am using. And I found another way (kernel events) to identify wiz light in the network.

**Comment by srisham** [comment]
@WitherredAway,

I found the issue. I was testing with WSL & Virtual machine but it seems that it is unable to access Wifi Interface. So any device scanning or UDP broadcast failed to communicate with Bulb.
Tried with Linux Desktop and UDP broadcast worked.

```
root@sri-HP-Pavilion-g6-Notebook-PC:~# iw dev
phy#0
        Interface wlp2s0b1
                ifindex 3
                wdev 0x1
                addr e*********2
                ssid RouterMaskeed
                type managed
                channel 11 (2462 MHz), width: 20 MHz, center1: 2462 MHz
                txpower 19.00 dBm

root@sri-HP-Pavilion-g6-Notebook-PC:~# wizlight discover
Set the broadcast address: 192.168.1.255
Search for bulbs in 192.168.1.255 ...
{'ip_address': '192.168.1.152', 'mac_address': 'd**********d'}
```

**Comment by WitherredAway** [comment]
Gotcha, thanks!

**Comment by gitagogaming** [comment]
I am currently trying to connect with a windows 10 machine and auto discovery is not working.. 
When I put in the lights IP it works just fine.  

I have not noticed any setting in my router specifying UDP communication so unsure if this is an issue on my side or not
