### ISSUE TITLE
Setup.py is broken

### ISSUE THREAD

**Issue by tmckay1** [sbidy/pywizlight#5]
Running `sudo python3 setup.py` does not work because after this commit: https://github.com/sbidy/pywizlight/commit/de28d146fc26a0b35002597765c91ab53ff5c2c9#diff-41caa14b44b8bb1cc66b4ee093105957R3, the `get_version()` function cannot find the version because the single quotes were replaced with double quotes in `_version.py`. Also, would be nice for installation instructions for someone looking to download this and get started right away

**Comment by sbidy** [comment]
Fixed - please review and close 😉
