### ISSUE TITLE
Event Loop throws runtime error

### ISSUE THREAD

**Issue by Raynman77** [sbidy/pywizlight#6]
When using `loop = asyncio.get_event_loop()` as per the example and then in my coroutine assigning `loop = loop` I get a runtime error. However if I omit creating/getting the event thread all together this code works just fine and I am able to control my wiz lights just fine. Explanation?

![image](https://user-images.githubusercontent.com/16449459/91791827-196e0b80-ebe2-11ea-9ea0-8ce07095a9fa.png)

**Comment by sbidy** [comment]
Please reopen if still exists.
