### ISSUE TITLE
WiZmote?

### ISSUE THREAD

**Issue by spencerthayer** [sbidy/pywizlight#68]
I already asked this on the [Home Assistant integration repository](https://github.com/sbidy/wiz_light/issues/122) but maybe this is better asked here. Does this work with the [WiZMote](https://www.wizconnected.com/en-US/consumer/products/046677603595/)? If so how do we integrate that?

**Comment by sbidy** [comment]
No this does not work with this. The remote is an Bluetooth device.

You can use any Bluetooth-To-WiFi bridge to use the remote.

But the integration is only able to control the bulbs and other WiFi connected devices.

**Comment by sbidy** [comment]
Short update on that - the Remote is WiFi but it will use a special ESP WiFi trigger package.
The remote can't be implemented into the lib because it is based on standard UDP connections.
