### ISSUE TITLE
Additional or alternative scenes?

### ISSUE THREAD

**Issue by eibanez** [sbidy/pywizlight#69]
Last night I downloaded the Android APK of the app and poking around I found the images that represent each scene. I did find all the images for the scenes listed in `pywizlight/scenes.py`

I did find a few additional images, which correspond to alternative versions of scenes listed in the repo. It seems to me that they are animated scenes that only use the white LEDs. The scene names have `_tw` appended to them (maybe for True White?).

For instance, this is what the file for `christmas` looks like (`scene_christmas_big.png`):

![image](https://user-images.githubusercontent.com/438494/112724582-0d30ff00-8ee2-11eb-96f4-b42246c2df6e.png)

And this is what the file for `christmas_tw` looks like (`scene_christmas_tw_big.png`):
![image](https://user-images.githubusercontent.com/438494/112724591-16ba6700-8ee2-11eb-97a1-0305b11ea32a.png)

There are five scenes that have this alternative version:
- `bedtime_tw`
- `christmas_tw`
- `relax_tw`
- `tv_time_tw`
- `wakeup_tw`

I don't have an android device, but these scenes are not listed in the iOS app at all. I wonder if there is an additional parameter that needs to be implemented to activate them.

cc: @vodovozovge @angadsingh

**Comment by vodovozovge** [comment]
hey @eibanez 

we indeed have some scenes with alternative icons. Some of them exist only for Tunable White (CCT only, Whites) bulbs (hence the "tw"), some for both Tunable Whites and Dimmable Whites ("dw")

They are tuned to work on the bulbs that don't have RGB LEDs and to make the app a bit nicer, we added additional assets to better represent what happens on the lights.

To activate the scene you simply need tunable white light ;)

**Comment by eibanez** [comment]
Oh, that makes sense! Thanks for the prompt response.
