### ISSUE TITLE
Support motion sensor enable / disable

### ISSUE THREAD

**Issue by djacobson** [sbidy/pywizlight#88]
I was curious if this API might expose the Enable / Disable setting for the WiZ Motion Sensor in the room settings? I wish WiZ made this setting schedulable but, alas, no. :( If I could program it, that would be cool. :)

**Comment by djacobson** [comment]
A possible work-around, since I'm simply trying to disable the motion sensor for the night... If I set "Detection Delay" to ~6 hrs (or however long through the night), the motion sensor will be ignored for that amount of time after a manual lights status change :through the (WiZ) app". Would a scheduled programmatic light bulb change via pywizlight "look like" the same "manual" status change via the WiZ app?

**Comment by rgomezjnr** [comment]
Here's my 2 cents, if anyone else has more to add:
https://github.com/rgomezjnr/wizcon/issues/3#issuecomment-933912847

**Comment by bdraco** [comment]
It doesn't look like there is an api available for the UDP local api to control if the motion sensor is enabled or disabled.
