### ISSUE TITLE
AssertionError in pywizlight.discovery

### ISSUE THREAD

**Issue by sbidy** [sbidy/pywizlight#94]
Issue if try to send broadcast for discovery.

MyPy Error:
`
Incompatible types in assignment (expression has type "BaseTransport", variable has type "Optional[DatagramTransport]")`

Exception:
```
Exception in callback BroadcastProtocol.connection_made(<_SelectorDat...e, bufsize=0>>)
handle: <Handle BroadcastProtocol.connection_made(<_SelectorDat...e, bufsize=0>>)>
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Stephan\AppData\Roaming\Python\Python37\site-packages\pywizlight\discovery.py", line 66, in connection_made
    transport, DatagramTransport
AssertionError
```
Workaround with:
https://github.com/sbidy/pywizlight/blob/21c826301be042c4d22e0cc0d9a2a71ff4e7552b/pywizlight/discovery.py#L66

Maybe @akx can help me here? Is this a cast issue?

**Comment by akx** [comment]
Sure! Yeah, I think we can make that type assertion typecheck-time only. Just a sec, whipping up a PR 👨‍🍳

**Comment by akx** [comment]
@sbidy Please see #95 :) Sorry for the hassle...

**Comment by sbidy** [comment]
Mypy is still not happy with it.
`Incompatible types in assignment (expression has type "BaseTransport", variable has type "Optional[DatagramTransport]")`

Maybe add here a whitelisting for that typing.

**Comment by bdraco** [comment]
This can be closed as its now cast
